require('express-async-errors')
const express = require('express')
const bodyParser = require('body-parser')
const author = require('./routes/author')
const book = require('./routes/book')
const winston=require('winston')
const app = express()
require('./startup/config.js')(app,express)
require('./startup/db.js')()
winston.add(new winston.transports.File({filename:'logfile.log'}))
app.use('/api/author',author)
app.use('/api/book',book)

const port = process.env.port || 3000;
app.listen(port,()=>console.log(`app listening on port ${port}`))